project_id = "fkvijsazmfvmlmtoyhsf"

[functions.create-users]
verify_jwt = false

[functions.sync-students]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.analyze-book-cover]
verify_jwt = false

[functions.canva-auth]
verify_jwt = false

[functions.canva-api]
verify_jwt = false

[functions.notebook-chat]
verify_jwt = false
