project_id = "fkvijsazmfvmlmtoyhsf"

[functions.create-users]
verify_jwt = false

[functions.sync-students]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.analyze-book-cover]
verify_jwt = false
